version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: listing
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  dbclient:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ramunas@email.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "8889:80"